// @vitest-environment jsdom
import React from "react";
import { afterEach, expect, it } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { ChronicleExhibition } from "../components/chronicle/ChronicleExhibition";
import { researchRoutes } from "../lib/chronicle/researchRoutes";
const routes=["高压气态储氢","液氢储能","固态储氢","化学载体储氢"];
afterEach(cleanup);
function selectRoute(name:string){fireEvent.change(screen.getByRole("combobox",{name:"家族"}),{target:{value:"氢储能"}});fireEvent.change(screen.getByRole("combobox",{name:"路线"}),{target:{value:name}});}
it("hydrogen routes own verified chronology, media, six chapters and energy boundaries",()=>{for(const name of routes){const r=researchRoutes[name];expect(r?.name).toBe(name);expect(r.timeline.length).toBeGreaterThanOrEqual(6);expect(r.materials.length).toBeGreaterThanOrEqual(3);expect(r.chapters.map(c=>c.id)).toEqual(["history","materials","papers","industry","market","storage"]);expect(r.showMarketChart).toBe(false);expect(r.papers).toBeTruthy();expect(r.storage).toBeTruthy();}});
it("hydrogen market never uses electric-storage total as route capacity",()=>{render(<ChronicleExhibition/>);for(const name of routes){selectRoute(name);fireEvent.click(screen.getByRole("button",{name:"政策市场"}));expect(screen.queryByText("阅读固态完整样板")).toBeNull();expect(screen.getByRole("region",{name:"技术展厅"}).querySelector("svg")).toBeNull();}});
it("hydrogen papers open their route chapter and preserve selection on return",()=>{render(<ChronicleExhibition/>);for(const name of routes){selectRoute(name);fireEvent.click(screen.getByRole("button",{name:"论文"}));fireEvent.click(screen.getByRole("button",{name:"进入详解"}));expect(screen.getByRole("heading",{name:researchRoutes[name].chapters.find(c=>c.id==="papers")!.title,level:2})).toBeTruthy();expect(screen.queryByText("6000次")).toBeNull();fireEvent.click(screen.getByRole("button",{name:/返回现场/}));expect(screen.getByRole("button",{name:"论文"}).getAttribute("aria-pressed")).toBe("true");}});

it("hydrogen facts distinguish vessel and system mass, cooling power and separate hydride conditions",()=>{const gas=researchRoutes[routes[0]],liquid=researchRoutes[routes[1]],solid=researchRoutes[routes[2]],carrier=researchRoutes[routes[3]];expect(gas.timeline.find(n=>n.yearNumber===2014)?.facts.flat().join(' ')).toContain('5.7');expect(liquid.timeline.find(n=>n.yearNumber===2017)?.facts.flat().join(' ')).toContain('390');const mg=solid.timeline.find(n=>n.yearNumber===2025)!;expect(mg.facts.flat().join(' ')).toContain('5.28');expect(mg.facts.flat().join(' ')).toContain('1.96');expect(carrier.timeline.find(n=>n.yearNumber===2024)?.detail).toContain('燃料热值');expect(gas.companies.some(c=>c.id==='hydrogen-gas-enric')).toBe(true);expect(carrier.companies.some(c=>c.id==='hydrogen-carrier-sinopec-lohc')).toBe(true);});
it("hydrogen stage uses matching real media and material concepts, and year survives reading",()=>{render(<ChronicleExhibition/>);for(const name of routes){selectRoute(name);fireEvent.click(screen.getByRole('button',{name:'历史'}));const stage=screen.getByRole('region',{name:'技术展厅'});expect(stage.querySelector('img')?.getAttribute('data-kind')).toBe('real-photo');const first=screen.getByRole('navigation',{name:'历史年份'}).querySelector('button')!;const label=first.getAttribute('aria-label')!;fireEvent.click(first);fireEvent.click(screen.getByRole('button',{name:'进入详解'}));fireEvent.click(screen.getByRole('button',{name:/返回现场/}));expect(screen.getByRole('button',{name:label}).getAttribute('aria-pressed')).toBe('true');fireEvent.click(screen.getByRole('button',{name:'材料'}));expect(screen.getByRole('region',{name:'技术展厅'}).querySelector('img')?.getAttribute('data-kind')).toBe('ai-illustration');}});
