// @vitest-environment jsdom
import React from "react";
import { afterEach, expect, it } from "vitest";
import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { ChronicleExhibition } from "../components/chronicle/ChronicleExhibition";
import { researchRoutes } from "../lib/chronicle/researchRoutes";
afterEach(cleanup);
const open=()=>render(<ChronicleExhibition/>);
it("all three researched routes map the six shared IDs to actual chapters",()=>{
 for(const research of Object.values(researchRoutes)) for(const id of ["history","materials","papers","industry","market","storage"]) expect(research.chapters.find(x=>x.id===id)).toBeTruthy();
});
it("the same six navigation controls remain in display and reading",()=>{open(); const names=()=>within(screen.getByRole("navigation",{name:"编年史栏目"})).getAllByRole("button").map(x=>x.textContent);expect(names()).toEqual(["历史","材料","论文","企业","政策市场","储能适配"]);fireEvent.click(screen.getByRole("button",{name:/进入详解/}));expect(names()).toHaveLength(6);fireEvent.click(screen.getByRole("button",{name:"论文"}));expect(screen.getByRole("button",{name:"论文"}).getAttribute("aria-pressed")).toBe("true");fireEvent.click(screen.getByRole("button",{name:/返回现场/}));expect(screen.getByRole("button",{name:"论文"}).getAttribute("aria-pressed")).toBe("true");});
it("history preserves its selected year after reading and changing columns",()=>{open();fireEvent.click(screen.getByRole("button",{name:/^2025，/}));fireEvent.click(screen.getByRole("button",{name:/进入详解/}));expect(screen.getByText(/1000次54.9%/)).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"材料"}));fireEvent.click(screen.getByRole("button",{name:/返回现场/}));fireEvent.click(screen.getByRole("button",{name:"历史"}));expect(screen.getByRole("button",{name:/^2025，/}).getAttribute("aria-pressed")).toBe("true");});
it("material choice and the contextual image are retained in reading",()=>{open();fireEvent.click(screen.getByRole("button",{name:"材料"}));fireEvent.change(screen.getByRole("combobox",{name:"材料路线"}),{target:{value:"halide"}});const src=screen.getByRole("img").getAttribute("src");fireEvent.click(screen.getByRole("button",{name:/进入详解/}));expect(screen.getByRole("region",{name:"研究详解"}).getAttribute("style")).toContain(src);expect(screen.getByRole("combobox",{name:"材料路线"}).getAttribute("value")??(screen.getByRole("combobox",{name:"材料路线"}) as HTMLSelectElement).value).toBe("halide");});
it("source lines move to collapsed references while tables remain",()=>{open();fireEvent.click(screen.getByRole("button",{name:/进入详解/}));expect(screen.queryByText(/上方年份可以/)).toBeNull();fireEvent.click(screen.getByRole("button",{name:"论文"}));expect(document.querySelectorAll("table").length).toBeGreaterThan(0);const refs=screen.getByText("参考资料").closest("details")!;expect(refs.open).toBe(false);expect(refs.querySelectorAll("a").length).toBeGreaterThan(0);});
it("AI visual has only one neutral label",()=>{open();fireEvent.click(screen.getByRole("button",{name:"材料"}));fireEvent.change(screen.getByRole("combobox",{name:"材料路线"}),{target:{value:"oxide"}});expect(screen.queryByText("AI结构示意 · 非实验图像")).toBeNull();expect(screen.getAllByText("示意图")).toHaveLength(1);});
it("policy and storage columns have evidence and real research destinations",()=>{open();fireEvent.click(screen.getByRole("button",{name:"政策市场"}));expect(screen.getByText("中国新型储能（全部技术）")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"储能适配"}));fireEvent.click(screen.getByRole("button",{name:/进入详解/}));expect(screen.getByRole("region",{name:"研究详解"})).toBeTruthy();});
it("lithium and sodium have independent six-column content",()=>{open();for(const route of ["锂离子","钠离子"]){fireEvent.change(screen.getByRole("combobox",{name:"路线"}),{target:{value:route}});fireEvent.click(screen.getByRole("button",{name:"论文"}));fireEvent.click(screen.getByRole("button",{name:/进入详解/}));expect(screen.queryByText(/6000次/)).toBeNull();fireEvent.click(screen.getByRole("button",{name:/返回现场/}));}});
it("lead acid independent research does not display solid state numerical evidence",()=>{open();fireEvent.change(screen.getByRole("combobox",{name:"路线"}),{target:{value:"铅酸"}});fireEvent.click(screen.getByRole("button",{name:"论文"}));expect(screen.queryByText("6000次")).toBeNull();expect(screen.getByRole("button",{name:"进入详解"})).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"企业"}));expect(screen.queryByText(/美国固态锂金属电池开发企业/)).toBeNull();expect(screen.queryByText(/28.11亿美元/)).toBeNull();});
