// Generated by scripts/generate-api-types.mjs from backend/openapi.json.
// DO NOT EDIT BY HAND — run `npm run generate:types` after backend schema changes.

export interface ApiSchemas {
  AnalysisCreate: {
    recipe: string;
    parameters?: Record<string, unknown>;
  };
  AnalysisReportPayload: {
    quick_understanding: string;
    quick_prompt_version: string;
    quick_schema_version: string;
    quick_evidence_status: string;
    layman_understanding: string;
    layman_prompt_version: string;
    layman_schema_version: string;
    layman_evidence_status: string;
    reviewer_analysis: string;
    reviewer_prompt_version: string;
    reviewer_schema_version: string;
    reviewer_evidence_status: string;
  };
  AnalysisReportType: "quick_understanding" | "layman_understanding" | "reviewer_analysis";
  ApiKeyStatus: {
    configured: boolean;
    last4?: string | null;
  };
  BackupDeleteResponse: {
    deleted_name: string;
    remaining_count: number;
  };
  BackupResponse: {
    name: string;
    created_at: string;
    size_bytes: number;
    sha256: string;
    file_count: number;
  };
  Body_create_audio_defense_turn_api_v1_contest_defense_sessions__session_id__audio_post: {
    file: string;
  };
  Body_create_import_api_v1_scientific_imports_post: {
    file: string;
  };
  Body_upload_paper_api_v1_papers_upload_post: {
    file: string;
  };
  Body_upload_source_api_v1_contests__project_id__sources_upload_post: {
    file: string;
  };
  CampusAnalysisResponse: {
    status: "pending" | "ready" | "failed" | "deferred" | "not_configured";
    method: "rule" | "ai" | "mock";
    model: string | null;
    prompt_version: string | null;
    unknowns: Array<string>;
    evidence: Array<ApiSchemas["CampusEvidenceResponse"]>;
  };
  CampusDateResponse: {
    kind: string;
    day: string;
    evidence: string;
  };
  CampusEventList: {
    items: Array<ApiSchemas["CampusEventResponse"]>;
    total: number;
    counts: Record<string, number>;
    days: number;
  };
  CampusEventResponse: {
    id: number;
    title: string;
    category: string | null;
    subtype: string | null;
    category_basis: "ai" | "mock" | "rule" | "unverified";
    subtype_basis: "ai" | "mock" | "rule" | "unverified";
    tags: Array<string>;
    competition_type: string | null;
    competition_tracks: Array<string>;
    stage: string | null;
    audience: string | null;
    action: string | null;
    summary: string;
    key_points: Array<string>;
    analysis: ApiSchemas["CampusAnalysisResponse"];
    feed_status: "recent" | "unknown" | "archive";
    date_basis: "published" | "future_date" | "past_date" | "unknown" | "conflict";
    excerpt: string;
    dates: Array<ApiSchemas["CampusDateResponse"]>;
    published_on: string | null;
    priority: number;
    followed: boolean;
    conflict: boolean;
    archived: boolean;
    origins: Array<ApiSchemas["CampusOriginResponse"]>;
    updated_at: string;
  };
  CampusEventUpdate: {
    followed: boolean;
  };
  CampusEvidenceResponse: {
    field: string;
    quote: string;
    url: string;
  };
  CampusNoticeList: {
    items: Array<ApiSchemas["CampusNoticeResponse"]>;
  };
  CampusNoticeResponse: {
    id: number;
    event_id: number;
    title: string;
    body: string;
    kind: string;
    read_at: string | null;
    created_at: string;
    url: string | null;
    source_name: string | null;
  };
  CampusOriginResponse: {
    source_id: number;
    name: string;
    url: string;
    published_on: string | null;
  };
  CampusPublicLinkList: {
    items: Array<ApiSchemas["CampusPublicLinkResponse"]>;
    total: number;
    counts: Record<string, number>;
    days: number;
  };
  CampusPublicLinkOriginResponse: {
    source_id: number;
    name: string;
    url: string;
  };
  CampusPublicLinkResponse: {
    url: string;
    title: string;
    published_on: string | null;
    first_seen_at: string;
    last_seen_at: string;
    evidence_level: "link_only";
    origins: Array<ApiSchemas["CampusPublicLinkOriginResponse"]>;
  };
  CampusSourceList: {
    items: Array<ApiSchemas["CampusSourceResponse"]>;
  };
  CampusSourceResponse: {
    id: number;
    key: string;
    name: string;
    group: string;
    url: string;
    priority: number;
    enabled: boolean;
    status: string;
    detail: string;
    last_checked_at: string | null;
    last_success_at: string | null;
    next_check_at: string | null;
    robots_status: string;
    activation_state: "never_enabled" | "enabled" | "paused";
    access_state: "public" | "login_required" | "unreachable" | "unknown";
    coverage: "column" | "homepage" | "unverified";
  };
  CampusSourceUpdate: {
    enabled: boolean;
  };
  ClaimEvidenceResponse: {
    chunk_id: number;
    page_number: number | null;
    section: string;
    excerpt: string;
    source_scope: "fulltext" | "abstract" | "note";
    parse_confidence: number;
    similarity: number;
    locator: string;
    source_locations?: Array<ApiSchemas["EvidenceLocationResponse"]>;
  };
  CleanupConfirm: {
    token: string;
  };
  CleanupPreviewResponse: {
    token: string;
    paths: Array<string>;
    bytes_reclaimable: number;
  };
  CloudEnhanceRequest: {
    confirmed: boolean;
  };
  CloudEnhanceResponse: {
    run_id: number;
    page_number: number;
    text: string;
    confidence: number;
    confirmation_status: string;
    evidence_status: string;
  };
  ComparisonPaperResponse: {
    paper_id: number;
    title: string;
    evidence_basis: string;
    research_focus: string;
    citation_count: number;
  };
  ContestDefenseSessionCreate: {
    mode?: "text" | "voice";
  };
  ContestDefenseSessionResponse: {
    id: number;
    project_id: number;
    mode: "text" | "voice";
    created_at: string;
  };
  ContestDefenseTurnCreate: {
    answer: string;
  };
  ContestDefenseTurnResponse: {
    id: number;
    session_id: number;
    question: string;
    answer: string;
    feedback: string;
    transcript: string;
    created_at: string;
  };
  ContestDeleteRequest: {
    confirmation_title: string;
  };
  ContestMilestoneCreate: {
    title: string;
    due_date: string;
  };
  ContestMilestoneResponse: {
    id: number;
    title: string;
    due_date: string;
    source: "manual" | "confirmed_rule";
    completed: boolean;
  };
  ContestProjectCreate: {
    title: string;
    competition_name?: string;
  };
  ContestProjectListResponse: {
    items: Array<ApiSchemas["ContestProjectResponse"]>;
  };
  ContestProjectResponse: {
    id: number;
    title: string;
    competition_name: string;
    summary: string;
    research_question: string;
    innovation: string;
    method: string;
    evidence: string;
    feasibility: string;
    expected_outcomes: string;
    risks: string;
    resources: string;
    created_at: string;
    updated_at: string;
  };
  ContestProjectUpdate: {
    title?: string | null;
    competition_name?: string | null;
    summary?: string | null;
    research_question?: string | null;
    innovation?: string | null;
    method?: string | null;
    evidence?: string | null;
    feasibility?: string | null;
    expected_outcomes?: string | null;
    risks?: string | null;
    resources?: string | null;
  };
  ContestRubricCheckItemResponse: {
    id: number;
    rubric_item_id: number;
    title: string;
    status: "satisfied" | "partial" | "missing";
    evidence: Array<string>;
    questions: Array<string>;
  };
  ContestRubricCheckResponse: {
    items: Array<ApiSchemas["ContestRubricCheckItemResponse"]>;
  };
  ContestRubricItemResponse: {
    id: number;
    title: string;
    description: string;
    weight: number | null;
    citations: Array<string>;
    status: "draft" | "confirmed";
  };
  ContestRuleResponse: {
    id: number;
    title: string;
    description: string;
    deadline: string | null;
    citations: Array<string>;
    status: "draft" | "confirmed";
  };
  ContestRuleSetResponse: {
    status: "draft" | "confirmed";
    rules: Array<ApiSchemas["ContestRuleResponse"]>;
    rubric_items: Array<ApiSchemas["ContestRubricItemResponse"]>;
  };
  ContestRulesConfirmRequest: {
    confirmed: boolean;
  };
  ContestSourceResponse: {
    id: number;
    project_id: number;
    name: string;
    source_type: "pdf" | "text" | "image" | "csv";
    sha256: string;
    status: string;
    locator_count: number;
    created_at: string;
  };
  ContestTextSourceCreate: {
    name: string;
    source_type?: "text";
    content: string;
  };
  ContestTimelineResponse: {
    items: Array<ApiSchemas["ContestMilestoneResponse"]>;
  };
  DatasetCreate: {
    parse_run_id?: number | null;
    visual_id?: number | null;
    crop_id?: number | null;
    source_type: string;
    domain: string;
    dataset_type: string;
    data: Record<string, unknown>;
    units?: Record<string, unknown>;
    parameters?: Record<string, unknown>;
    confidence: number;
  };
  DatasetPatch: {
    data?: Record<string, unknown> | null;
    units?: Record<string, unknown> | null;
    parameters?: Record<string, unknown> | null;
    confirmed?: boolean | null;
  };
  DocumentAiCapabilitiesResponse: {
    cpu: boolean;
    gpu: boolean;
    preferred_device: "cpu" | "gpu";
  };
  DocumentAiCurrentTaskResponse: {
    type: string;
    id: number;
    paper_id: number;
    progress: number;
  };
  DocumentAiInstallResponse: {
    status: string;
  };
  DocumentAiLocalModelResponse: {
    id: string;
    version: string;
    installed: boolean;
    status: string;
    download_size_mb: number;
    error: string | null;
  };
  DocumentAiStatusResponse: {
    local_model: ApiSchemas["DocumentAiLocalModelResponse"];
    capabilities: ApiSchemas["DocumentAiCapabilitiesResponse"];
    current_task: ApiSchemas["DocumentAiCurrentTaskResponse"] | null;
  };
  DocumentParsersStatusResponse: {
    docling: ApiSchemas["ParserCapabilityResponse"];
  };
  DuplicateReasonResponse: {
    kind: string;
    paper_id: number;
  };
  EvidenceBboxResponse: {
    left: number;
    top: number;
    right: number;
    bottom: number;
  };
  EvidenceLocationResponse: {
    page_number: number;
    element_id: string;
    bbox: ApiSchemas["EvidenceBboxResponse"];
    coord_origin: "TOPLEFT";
    page_width: number;
    page_height: number;
  };
  ExperimentDesignCreate: {
    idea_id?: number | null;
    contest_project_id?: number | null;
    title: string;
    variables?: string;
    controls?: string;
    replication?: string;
    randomization?: string;
    measurement?: string;
    statistics?: string;
    stopping_criteria?: string;
    resources?: string;
    risks?: string;
  };
  ExperimentDesignPatch: {
    title?: string | null;
    variables?: string | null;
    controls?: string | null;
    replication?: string | null;
    randomization?: string | null;
    measurement?: string | null;
    statistics?: string | null;
    stopping_criteria?: string | null;
    resources?: string | null;
    risks?: string | null;
  };
  ExperimentDesignResponse: {
    id: number;
    idea_id: number | null;
    contest_project_id: number | null;
    title: string;
    variables: string;
    controls: string;
    replication: string;
    randomization: string;
    measurement: string;
    statistics: string;
    stopping_criteria: string;
    resources: string;
    risks: string;
    deterministic_findings: Array<Record<string, string>>;
    ai_review: string;
    created_at: string;
    updated_at: string;
  };
  ExternalComparisonCurrentPaperResponse: {
    paper_id: number;
    title: string;
    evidence_basis: string;
  };
  ExternalComparisonPaperResponse: {
    source: "openalex" | "crossref" | "arxiv" | "semantic_scholar";
    external_id: string;
    title: string;
    authors: Array<string>;
    abstract: string;
    landing_url: string;
    evidence_basis: string;
  };
  ExternalComparisonRequest: {
    question: string;
  };
  ExternalComparisonResponse: {
    question: string;
    current_paper: ApiSchemas["ExternalComparisonCurrentPaperResponse"];
    external_papers: Array<ApiSchemas["ExternalComparisonPaperResponse"]>;
    answer_markdown: string;
    evidence_status: string;
    provider: string;
    model_name: string;
  };
  FormulaTranscriptionResponse: {
    crop_id: number;
    paper_id: number;
    page_number: number;
    latex: string;
    evidence_status: string;
    model_name: string;
  };
  GlossaryAskRequest: {
    question: string;
    history?: Array<ApiSchemas["GlossaryHistoryTurn"]>;
  };
  GlossaryAskResponse: {
    question: string;
    answer: string;
    evidence_status: string;
    provider: string;
    model_name: string;
  };
  GlossaryGenerateResponse: {
    terms: Array<ApiSchemas["GlossaryTerm"]>;
    evidence_status: string;
    provider: string;
    model_name: string;
  };
  GlossaryHistoryTurn: {
    question: string;
    answer: string;
  };
  GlossaryTerm: {
    term: string;
    explanation: string;
  };
  HTTPValidationError: {
    detail?: Array<ApiSchemas["ValidationError"]>;
  };
  KnowledgeAnswerResponse: {
    question: string;
    answer_markdown: string;
    citations: Array<ApiSchemas["KnowledgeCitationResponse"]>;
    evidence_status: string;
    confidence: ApiSchemas["KnowledgeConfidenceResponse"];
    provider: string;
    model_name: string;
  };
  KnowledgeAskRequest: {
    question: string;
    max_citations?: number;
    history?: Array<ApiSchemas["KnowledgeHistoryTurn"]>;
  };
  KnowledgeCitationResponse: {
    chunk_id?: number | null;
    evidence_key?: string | null;
    citation_id: number;
    paper_id: number;
    paper_title: string;
    page_number: number | null;
    section: string;
    excerpt: string;
    source_scope: "fulltext" | "abstract" | "note";
    parse_confidence: number;
    similarity: number;
    source_locations?: Array<ApiSchemas["EvidenceLocationResponse"]>;
  };
  KnowledgeConfidenceResponse: {
    level: "低" | "中" | "高";
    explanation: string;
  };
  KnowledgeHistoryTurn: {
    question: string;
    answer_markdown: string;
  };
  KnowledgeReindexResponse: {
    indexed_papers: number;
    indexed_chunks: number;
    skipped_papers: number;
    embedding_provider: string;
    embedding_model: string;
  };
  KnowledgeStatusResponse: {
    total_papers: number;
    indexed_papers: number;
    stale_papers: number;
    chunk_count: number;
    embedding_provider: string;
    embedding_model: string;
    ready: boolean;
    message: string;
  };
  LearningAnalyticsDailyResponse: {
    date: string;
    reviews: number;
    attempts: number;
    completed_tasks: number;
  };
  LearningAnalyticsResponse: {
    days: 7 | 30 | 90;
    from_date: string;
    to_date: string;
    history_start_date: string | null;
    daily: Array<ApiSchemas["LearningAnalyticsDailyResponse"]>;
    rating_distribution: Record<string, number>;
    correct_rate: number | null;
    mastery_distribution: Record<string, number>;
    due_review_count: number;
    weaknesses: Array<ApiSchemas["LearningAnalyticsWeaknessResponse"]>;
  };
  LearningAnalyticsWeaknessResponse: {
    concept: string;
    score: number;
    pack_count: number;
    occurrence_count: number;
    recurrence_count: number;
  };
  LearningAttemptCreate: {
    answer: string;
  };
  LearningAttemptResponse: {
    id: number;
    question_id: number;
    answer: string;
    result: "correct" | "partial" | "wrong" | "pending_self_review";
    self_rating: string | null;
    correct_answer?: string | null;
    explanation?: string | null;
    reference_points?: Array<string> | null;
    feedback_markdown?: string | null;
    feedback_provider?: string | null;
    feedback_model_name?: string | null;
    feedback_prompt_version?: string | null;
    feedback_evidence_status?: string | null;
    feedback_generated_at?: string | null;
    created_at?: string | null;
  };
  LearningAttemptSelfRating: {
    self_rating: "答对" | "部分答对" | "答错";
  };
  LearningCardGenerateResponse: {
    cards: Array<ApiSchemas["LearningCardResponse"]>;
    status: string;
  };
  LearningCardListResponse: {
    items: Array<ApiSchemas["LearningCardResponse"]>;
  };
  LearningCardResponse: {
    id: number;
    pack_id: number | null;
    concept: string;
    generated_content: string;
    content: string;
    importance: string;
    common_mistake: string;
    evidence: Array<ApiSchemas["LearningEvidenceResponse"]>;
    is_user_edited: boolean;
    mastery_status: "未学习" | "学习中" | "已掌握";
    mastery_confirmed_at: string | null;
    position: number;
    review_state: ApiSchemas["LearningReviewStateResponse"] | null;
  };
  LearningCardUpdate: {
    concept?: string | null;
    content?: string | null;
    importance?: string | null;
    common_mistake?: string | null;
  };
  LearningDiffResponse: {
    added: Array<string>;
    removed: Array<string>;
    changed: Array<string>;
  };
  LearningEligiblePaperListResponse: {
    items: Array<ApiSchemas["LearningEligiblePaperResponse"]>;
  };
  LearningEligiblePaperResponse: {
    id: number;
    title: string;
    journal: string;
    published_date: string | null;
    available_reports: Array<string>;
  };
  LearningEvidenceResponse: {
    evidence_id: string;
    paper_id: number;
    paper_title: string;
    page_number: number | null;
    section: string;
    excerpt: string;
    source_scope: string;
  };
  LearningFeedbackRequest: {
    regenerate?: boolean;
  };
  LearningMasteryUpdate: {
    mastery_status: "未学习" | "学习中" | "已掌握";
  };
  LearningOrderUpdate: {
    ids: Array<number>;
  };
  LearningOverviewResponse: {
    packs: Array<ApiSchemas["LearningPackResponse"]>;
    today_tasks: Array<ApiSchemas["LearningPlanTaskResponse"]>;
    open_weaknesses: Array<ApiSchemas["LearningWeaknessResponse"]>;
    due_reviews: Array<ApiSchemas["LearningReviewItemResponse"]>;
    due_review_count: number;
  };
  LearningPackComparisonResponse: {
    left_pack_id: number;
    right_pack_id: number;
    source_changes: ApiSchemas["LearningDiffResponse"];
    cards: ApiSchemas["LearningDiffResponse"];
    questions: ApiSchemas["LearningDiffResponse"];
  };
  LearningPackCreate: {
    title: string;
    learning_goal?: string;
    paper_ids: Array<number>;
  };
  LearningPackDeleteRequest: {
    confirmation_title: string;
  };
  LearningPackListResponse: {
    items: Array<ApiSchemas["LearningPackResponse"]>;
  };
  LearningPackResponse: {
    id: number;
    title: string;
    learning_goal: string;
    cards_status: string;
    quiz_status: string;
    cards_prompt_version: string;
    cards_schema_version: string;
    quiz_prompt_version: string;
    quiz_schema_version: string;
    provider: string;
    model_name: string;
    lineage_id: string;
    version_number: number;
    lifecycle_status: "active" | "draft" | "archived";
    archived_at: string | null;
    last_error: string | null;
    created_at?: string | null;
    updated_at?: string | null;
    source_count: number;
    card_count: number;
    question_count: number;
    sources?: Array<ApiSchemas["LearningPackSourceResponse"]> | null;
    cards?: Array<ApiSchemas["LearningCardResponse"]> | null;
    questions?: Array<ApiSchemas["LearningQuestionResponse"]> | null;
    weaknesses?: Array<ApiSchemas["LearningWeaknessResponse"]> | null;
    plan?: ApiSchemas["LearningPlanResponse"] | null;
  };
  LearningPackSourceResponse: {
    id: number;
    paper_id: number | null;
    paper_title: string;
    available_reports: Array<string>;
    analysis_versions: Record<string, unknown>;
    analysis_hash?: string | null;
    evidence_scope?: string | null;
    source_has_newer_analysis: boolean;
  };
  LearningPaperCandidateListResponse: {
    items: Array<ApiSchemas["LearningPaperCandidateResponse"]>;
  };
  LearningPaperCandidateResponse: {
    id: number;
    title: string;
    journal: string;
    published_date: string | null;
    available_reports: Array<string>;
    eligible: boolean;
    is_read: boolean;
    fulltext_available: boolean;
    blocking_reasons: Array<string>;
  };
  LearningPlanResponse: {
    id: number;
    pack_id: number;
    start_date: string;
    end_date: string;
    weekdays: Array<number>;
    tasks: Array<ApiSchemas["LearningPlanTaskResponse"]>;
  };
  LearningPlanTaskListResponse: {
    items: Array<ApiSchemas["LearningPlanTaskResponse"]>;
  };
  LearningPlanTaskResponse: {
    id: number;
    pack_id: number;
    task_date: string;
    task_type: "card" | "quiz" | "weakness";
    card_id?: number | null;
    question_id?: number | null;
    weakness_id?: number | null;
    title: string;
    position?: number | null;
    completed_at?: string | null;
  };
  LearningPlanTaskUpdate: {
    completed: boolean;
  };
  LearningPlanUpsert: {
    start_date: string;
    end_date: string;
    weekdays: Array<number>;
  };
  LearningQuestionListResponse: {
    items: Array<ApiSchemas["LearningQuestionResponse"]>;
  };
  LearningQuestionResponse: {
    id: number;
    pack_id: number;
    question_type: "multiple_choice" | "true_false" | "fill_blank" | "short_answer";
    prompt: string;
    options: Array<string>;
    related_card_ids: Array<number>;
    evidence: Array<ApiSchemas["LearningEvidenceResponse"]>;
    position: number;
    attempts: Array<ApiSchemas["LearningAttemptResponse"]>;
  };
  LearningQuizGenerateResponse: {
    questions: Array<ApiSchemas["LearningQuestionResponse"]>;
    status: string;
  };
  LearningReviewItemResponse: {
    state: ApiSchemas["LearningReviewStateResponse"];
    pack_title: string;
    overdue_days: number;
    card: ApiSchemas["LearningCardResponse"];
  };
  LearningReviewQueueResponse: {
    today: string;
    items: Array<ApiSchemas["LearningReviewItemResponse"]>;
  };
  LearningReviewStateResponse: {
    id: number;
    pack_id: number;
    card_id: number;
    last_rating: "不会" | "模糊" | "基本掌握" | "已掌握";
    next_review_date: string | null;
    review_count: number;
    lapse_count: number;
    is_paused: boolean;
    last_reviewed_at: string | null;
  };
  LearningReviewSubmit: {
    rating: "不会" | "模糊" | "基本掌握" | "已掌握";
  };
  LearningReviewSubmitResponse: {
    state: ApiSchemas["LearningReviewStateResponse"];
    card: ApiSchemas["LearningCardResponse"];
  };
  LearningReviewUpdate: {
    next_review_date?: string | null;
    is_paused?: boolean | null;
  };
  LearningWeaknessCreate: {
    concept: string;
    description?: string;
    card_id?: number | null;
  };
  LearningWeaknessResponse: {
    id: number;
    pack_id: number;
    card_id: number | null;
    concept: string;
    description: string;
    source: "manual" | "quiz";
    occurrence_count: number;
    recurrence_count: number;
    is_resolved: boolean;
    resolved_at: string | null;
  };
  LearningWeaknessTaskCreate: {
    task_date: string;
  };
  LearningWeaknessUpdate: {
    concept?: string | null;
    description?: string | null;
  };
  ModelInstallRequest: {
    confirmed: boolean;
  };
  ModelListResponse: {
    provider: string;
    ok: boolean;
    models: Array<string>;
    message: string;
  };
  NoteUpdate: {
    content: string;
  };
  OcrCancelResponse: {
    id: number;
    status: string;
  };
  OcrRunListResponse: {
    items: Array<ApiSchemas["OcrRunResponse"]>;
  };
  OcrRunPageResponse: {
    page_number: number;
    source_type: "native" | "local_ocr" | "cloud_vision";
    confidence: number;
    confirmation_status: string;
  };
  OcrRunRequest: {
    mode?: "auto" | "full";
  };
  OcrRunResponse: {
    id: number;
    paper_id: number;
    version_number: number;
    mode: string;
    status: "queued" | "running" | "completed" | "failed" | "cancelled";
    engine: string;
    device: string;
    progress: number;
    quality_score: number;
    derivative_file_path: string | null;
    warnings: Array<string>;
    error_message: string;
    pages: Array<ApiSchemas["OcrRunPageResponse"]>;
  };
  OnboardingComplete: {
    study_mode?: string;
    research_topics?: Array<string>;
    keywords?: Array<string>;
    daily_task_time?: string;
    daily_budget?: number;
    monthly_budget?: number;
  };
  PaperClaimResponse: {
    id: number;
    paper_id: number;
    claim_text: string;
    claim_type: string;
    evidence_status: string;
    confidence: number;
    evidence: Array<ApiSchemas["ClaimEvidenceResponse"]>;
  };
  PaperClaimsResponse: {
    items: Array<ApiSchemas["PaperClaimResponse"]>;
  };
  PaperCollectionCounts: {
    all: number;
    favorites: number;
    read: number;
    unread: number;
  };
  PaperComparisonRequest: {
    paper_ids: Array<number>;
    question?: string;
  };
  PaperComparisonResponse: {
    question: string;
    comparison_markdown: string;
    papers: Array<ApiSchemas["ComparisonPaperResponse"]>;
    citations: Array<ApiSchemas["KnowledgeCitationResponse"]>;
    fairness_warnings: Array<string>;
    evidence_status: string;
    confidence: ApiSchemas["KnowledgeConfidenceResponse"];
    provider: string;
    model_name: string;
  };
  PaperDeleteRequest: {
    confirmation_title: string;
  };
  PaperDeleteResponse: {
    deleted: boolean;
    paper_id: number;
    file_deleted: boolean;
    warning?: string | null;
  };
  PaperDetailResponse: {
    paper: ApiSchemas["PaperResponse"];
    analysis: ApiSchemas["AnalysisReportPayload"] | null;
    note: string;
  };
  PaperImportRequest: {
    source: "openalex" | "crossref" | "arxiv" | "semantic_scholar";
    external_id: string;
    download_open_pdf?: boolean;
  };
  PaperImportResponse: {
    paper: ApiSchemas["PaperResponse"];
    created: boolean;
    duplicate_reason: ApiSchemas["DuplicateReasonResponse"] | null;
    download_attempted: boolean;
    download_succeeded: boolean;
    warning: string | null;
  };
  PaperNoteDraftRequest: {
    question: string;
    answer_markdown: string;
    citations: Array<ApiSchemas["KnowledgeCitationResponse"]>;
    kind?: "answer" | "challenge";
    evidence_status?: string;
  };
  PaperNoteDraftResponse: {
    markdown: string;
  };
  PaperPage: {
    items: Array<ApiSchemas["PaperResponse"]>;
    total: number;
    page: number;
    page_size: number;
    collection_counts: ApiSchemas["PaperCollectionCounts"];
  };
  PaperResponse: {
    id: number;
    original_filename: string | null;
    title: string;
    file_hash: string | null;
    file_size: number;
    page_count: number;
    extracted_text: string;
    parse_confidence: number;
    extraction_warning: string | null;
    fulltext_status: string;
    doi: string | null;
    arxiv_id: string | null;
    authors: Array<string>;
    abstract: string;
    journal: string;
    published_date: string | null;
    keywords: Array<string>;
    landing_url: string;
    pdf_url: string | null;
    oa_status: string;
    license: string | null;
    source_type: string;
    acquisition_status: string;
    article_type: string;
    is_favorite: boolean;
    is_read: boolean;
    active_parse_run_id: number | null;
    ocr_available: boolean;
    knowledge_index_stale: boolean;
    created_at: string;
  };
  PaperSearchResponse: {
    items: Array<ApiSchemas["SearchPaperResponse"]>;
    total_before_pagination: number;
    page: number;
    page_size: number;
    warnings: Array<string>;
    source_statuses: Array<ApiSchemas["SourceStatusResponse"]>;
  };
  PaperStateUpdate: {
    is_favorite: boolean;
    is_read: boolean;
  };
  PaperVisualCropCreate: {
    left: number;
    top: number;
    width: number;
    height: number;
    label?: string;
  };
  PaperVisualCropResponse: {
    id: number;
    paper_id: number;
    visual_id: number;
    page_number: number;
    left: number;
    top: number;
    width: number;
    height: number;
    label: string;
    analysis_markdown: string;
    structured_data: Record<string, unknown>;
    evidence_status: string;
    provider: string;
    model_name: string;
    created_at: string;
    updated_at: string;
  };
  PaperVisualResponse: {
    id: number;
    paper_id: number;
    page_number: number;
    kind: "figure" | "table" | "page";
    label: string;
    caption: string;
    analysis_markdown: string;
    evidence_status: string;
    provider: string;
    model_name: string;
    created_at: string;
    updated_at: string;
  };
  ParseCandidateComparisonResponse: {
    run_id: number;
    active: ApiSchemas["ParseComparisonMetricsResponse"];
    candidate: ApiSchemas["ParseComparisonMetricsResponse"];
  };
  ParseCandidateListResponse: {
    items: Array<ApiSchemas["ParseCandidateResponse"]>;
  };
  ParseCandidatePageResponse: {
    page_number: number;
    source_type: "docling";
    confidence: number;
    confirmation_status: string;
    page_width: number | null;
    page_height: number | null;
  };
  ParseCandidateRequest: {
    confirmed: boolean;
  };
  ParseCandidateResponse: {
    id: number;
    paper_id: number;
    version_number: number;
    mode: string;
    status: "queued" | "running" | "completed" | "failed" | "cancelled";
    engine: "docling";
    engine_version: string;
    device: string;
    progress: number;
    quality_score: number;
    warnings: Array<string>;
    error_message: string;
    pages: Array<ApiSchemas["ParseCandidatePageResponse"]>;
  };
  ParseComparisonMetricsResponse: {
    engine: string;
    characters: number;
    pages: number;
    tables: number;
    formulas: number;
    figures: number;
    duration_seconds: number | null;
    warnings: Array<string>;
  };
  ParserCapabilityResponse: {
    installed: boolean;
    artifacts_available: boolean;
    ready: boolean;
    version: string;
    reason: string;
  };
  ResearchChallengeResponse: {
    questions: Array<string>;
    criteria: Array<string>;
    citations: Array<ApiSchemas["KnowledgeCitationResponse"]>;
    evidence_status: string;
  };
  ResearchExportCreate: {
    title: string;
    export_type?: "markdown" | "docx" | "pptx";
    paper_ids?: Array<number>;
    dataset_ids?: Array<number>;
    analysis_ids?: Array<number>;
  };
  ResearchExportResponse: {
    id: number;
    title: string;
    export_type: "markdown" | "docx" | "pptx";
    selected_paper_ids: Array<number>;
    selected_dataset_ids: Array<number>;
    selected_analysis_ids: Array<number>;
    markdown: string;
    status: string;
    download_available: boolean;
    created_at: string;
  };
  ResearchIdeaCreate: {
    title: string;
    hypothesis?: string;
    evidence?: string;
    novelty?: string;
    falsification?: string;
    feasibility?: string;
    resources?: string;
    evidence_gaps?: string;
    paper_ids?: Array<number>;
    dataset_ids?: Array<number>;
  };
  ResearchIdeaGenerate: {
    paper_ids?: Array<number>;
    dataset_ids?: Array<number>;
  };
  ResearchIdeaPatch: {
    title?: string | null;
    hypothesis?: string | null;
    evidence?: string | null;
    novelty?: string | null;
    falsification?: string | null;
    feasibility?: string | null;
    resources?: string | null;
    evidence_gaps?: string | null;
    paper_ids?: Array<number> | null;
    dataset_ids?: Array<number> | null;
  };
  ResearchIdeaResponse: {
    id: number;
    title: string;
    source_mode: "user" | "selected_evidence";
    selected_paper_ids: Array<number>;
    selected_dataset_ids: Array<number>;
    hypothesis: string;
    evidence: string;
    novelty: string;
    falsification: string;
    feasibility: string;
    resources: string;
    evidence_gaps: string;
    ai_review: string;
    created_at: string;
    updated_at: string;
  };
  ResearchNewsItem: {
    title: string;
    source: string;
    url: string;
    published_date: string | null;
    summary: string;
  };
  ResearchNewsResponse: {
    items: Array<ApiSchemas["ResearchNewsItem"]>;
    warnings: Array<string>;
    fetched_at: string;
  };
  ResearchNotificationResponse: {
    id: number;
    subscription_id: number;
    run_id: number | null;
    kind: string;
    title: string;
    body: string;
    created_at: string;
    read_at: string | null;
  };
  ResearchReadingHighlight: {
    key: string;
    title_zh: string;
    points: Array<string>;
  };
  ResearchReadingHighlightsRequest: {
    recommendation_ids?: Array<number>;
    news_urls?: Array<string>;
  };
  ResearchReadingHighlightsResponse: {
    items: Array<ApiSchemas["ResearchReadingHighlight"]>;
  };
  ResearchRecommendationResponse: {
    id: number;
    subscription_id: number;
    run_id: number | null;
    source: string;
    external_id: string;
    identity_key: string;
    paper_snapshot: Record<string, unknown>;
    relevance_score: number;
    created_at: string;
    read_at: string | null;
  };
  ResearchRunResponse: {
    id: number;
    subscription_id: number;
    status: string;
    started_at: string;
    completed_at: string | null;
    discovered_count: number;
    recommended_count: number;
    source_statuses: Array<Record<string, unknown>>;
    warnings: Array<string>;
    error: string | null;
  };
  ResearchSubscriptionCreate: {
    name: string;
    query: string;
    sources?: Array<"openalex" | "crossref" | "arxiv" | "semantic_scholar">;
    year_from?: number | null;
    year_to?: number | null;
    open_access_only?: boolean;
    interval_hours?: number;
    enabled?: boolean;
  };
  ResearchSubscriptionDeleteRequest: {
    confirmation_name: string;
  };
  ResearchSubscriptionResponse: {
    id: number;
    name: string;
    query: string;
    sources: Array<"openalex" | "crossref" | "arxiv" | "semantic_scholar">;
    year_from: number | null;
    year_to: number | null;
    open_access_only: boolean;
    interval_hours: number;
    enabled: boolean;
    last_started_at: string | null;
    last_success_at: string | null;
    next_run_at: string | null;
    last_error: string | null;
    created_at: string;
    updated_at: string;
  };
  ResearchSubscriptionUpdate: {
    name?: string | null;
    query?: string | null;
    sources?: Array<"openalex" | "crossref" | "arxiv" | "semantic_scholar"> | null;
    year_from?: number | null;
    year_to?: number | null;
    open_access_only?: boolean | null;
    interval_hours?: number | null;
    enabled?: boolean | null;
  };
  SavedComparisonCreate: {
    question: string;
    comparison_markdown: string;
    papers: Array<ApiSchemas["ComparisonPaperResponse"]>;
    citations?: Array<ApiSchemas["KnowledgeCitationResponse"]>;
    fairness_warnings?: Array<string>;
    evidence_status: string;
    confidence: ApiSchemas["KnowledgeConfidenceResponse"];
    provider: string;
    model_name: string;
  };
  SavedComparisonListResponse: {
    items: Array<ApiSchemas["SavedComparisonSummary"]>;
  };
  SavedComparisonResponse: {
    id: number;
    title: string;
    paper_count: number;
    created_at: string;
    paper_ids: Array<number>;
    question: string;
    comparison_markdown: string;
    papers: Array<ApiSchemas["ComparisonPaperResponse"]>;
    citations: Array<ApiSchemas["KnowledgeCitationResponse"]>;
    fairness_warnings: Array<string>;
    evidence_status: string;
    confidence: ApiSchemas["KnowledgeConfidenceResponse"];
    provider: string;
    model_name: string;
  };
  SavedComparisonSummary: {
    id: number;
    title: string;
    paper_count: number;
    created_at: string;
  };
  SavedConversationCreate: {
    scope: "library" | "paper";
    paper_id?: number | null;
    title: string;
    turns: Array<ApiSchemas["SavedConversationTurn"]>;
  };
  SavedConversationListResponse: {
    items: Array<ApiSchemas["SavedConversationSummary"]>;
  };
  SavedConversationResponse: {
    id: number;
    scope: "library" | "paper";
    paper_id: number | null;
    title: string;
    created_at: string;
    updated_at: string;
    turns: Array<ApiSchemas["SavedConversationTurn"]>;
  };
  SavedConversationSummary: {
    id: number;
    scope: "library" | "paper";
    paper_id: number | null;
    title: string;
    created_at: string;
    updated_at: string;
  };
  SavedConversationTurn: {
    turn_index: number;
    question: string;
    answer_markdown: string;
    citations?: Array<ApiSchemas["KnowledgeCitationResponse"]>;
    evidence_status: string;
    confidence: ApiSchemas["KnowledgeConfidenceResponse"];
    provider: string;
    model_name: string;
  };
  ScientificAnalysisResponse: {
    id: number;
    dataset_id: number;
    recipe: string;
    algorithm_version: string;
    parameters: Record<string, unknown>;
    results: Record<string, unknown>;
    diagnostics: Record<string, unknown>;
    report_markdown: string;
    status: string;
    is_stale: boolean;
    error_message: string;
  };
  ScientificDatasetListResponse: {
    items: Array<ApiSchemas["ScientificDatasetResponse"]>;
  };
  ScientificDatasetResponse: {
    id: number;
    paper_id: number | null;
    name: string;
    import_id: number | null;
    idea_id: number | null;
    contest_project_id: number | null;
    parse_run_id: number | null;
    visual_id: number | null;
    crop_id: number | null;
    source_type: string;
    domain: string;
    dataset_type: string;
    data: Record<string, unknown>;
    units: Record<string, unknown>;
    parameters: Record<string, unknown>;
    confidence: number;
    confirmation_status: "pending" | "confirmed";
    is_stale: boolean;
    is_favorite: boolean;
    is_read: boolean;
    revision_count: number;
    quality: ApiSchemas["ScientificQualityResponse"];
  };
  ScientificDatasetStateUpdate: {
    is_favorite: boolean;
    is_read: boolean;
  };
  ScientificImportConfirm: {
    name: string;
    selected_sheet?: string | null;
    domain: string;
    dataset_type: string;
    units?: Record<string, string>;
    parameters?: Record<string, unknown>;
    paper_id?: number | null;
    idea_id?: number | null;
    contest_project_id?: number | null;
  };
  ScientificImportResponse: {
    id: number;
    original_filename: string;
    sha256: string;
    file_format: "csv" | "xlsx";
    available_sheets: Array<string>;
    selected_sheet: string | null;
    row_count: number;
    column_count: number;
    column_types: Record<string, string>;
    missing_values: Record<string, number>;
    range_values?: Record<string, number>;
    invalid_values?: Record<string, number>;
    preview: Array<Array<unknown | null>>;
    status: "preview" | "confirmed";
    created_at: string;
  };
  ScientificQualityResponse: {
    row_count: number;
    column_count: number;
    column_types: Record<string, string>;
    missing_values: Record<string, number>;
    range_values: Record<string, number>;
    invalid_values: Record<string, number>;
    reviewed: boolean;
    handling_policy: string;
  };
  ScientificRecipeResponse: {
    key: string;
    domain: string;
    algorithm_version: string;
    required_inputs: Array<string>;
    description: string;
  };
  SearchCandidateResponse: {
    source: "openalex" | "crossref" | "arxiv" | "semantic_scholar";
    external_id: string;
  };
  SearchPaperResponse: {
    source: "openalex" | "crossref" | "arxiv" | "semantic_scholar";
    external_id: string;
    import_source: "openalex" | "crossref" | "arxiv" | "semantic_scholar";
    import_external_id: string;
    already_imported: boolean;
    paper_id: number | null;
    title: string;
    authors: Array<string>;
    first_author: string;
    abstract: string;
    doi: string | null;
    arxiv_id: string | null;
    journal: string;
    published_date: string | null;
    year: number | null;
    keywords: Array<string>;
    landing_url: string;
    pdf_url: string | null;
    is_open_access: boolean;
    oa_status: string;
    license: string | null;
    sources: Array<"openalex" | "crossref" | "arxiv" | "semantic_scholar">;
    candidates: Array<ApiSchemas["SearchCandidateResponse"]>;
    relevance_score: number;
    relevance_reasons: Array<string>;
    article_type: string;
    citation_count: number;
    is_favorite: boolean;
    is_read: boolean;
  };
  SettingsResponse: {
    model_provider: string;
    model_name: string;
    vision_model: string;
    model_base_url: string;
    api_key: ApiSchemas["ApiKeyStatus"];
    timeout_seconds: number;
    backup_model: string;
    paper_budget: number;
    daily_budget: number;
    monthly_budget: number;
    campus_ai_daily_limit: number;
    campus_ai_max_tokens: number;
    onboarding_completed: boolean;
    document_vision_provider: string;
    document_vision_model: string;
    document_vision_base_url: string;
    document_vision_timeout_seconds: number;
    document_vision_api_key: ApiSchemas["ApiKeyStatus"];
  };
  SettingsUpdate: {
    model_provider?: string;
    model_name?: string;
    vision_model?: string;
    model_base_url?: string;
    api_key?: string | null;
    timeout_seconds?: number;
    backup_model?: string;
    paper_budget?: number;
    daily_budget?: number;
    monthly_budget?: number;
    campus_ai_daily_limit?: number;
    campus_ai_max_tokens?: number;
    document_vision_provider?: string;
    document_vision_model?: string;
    document_vision_base_url?: string;
    document_vision_timeout_seconds?: number;
    document_vision_api_key?: string | null;
  };
  SourceStatusResponse: {
    source: "openalex" | "crossref" | "arxiv" | "semantic_scholar";
    enabled: boolean;
    ok: boolean;
    message: string;
    result_count?: number | null;
    key_configured?: boolean | null;
  };
  StorageStatsResponse: {
    managed_bytes: number;
    managed_files: number;
    backup_bytes: number;
    backup_count: number;
    cache_bytes: number;
    cache_files: number;
  };
  TaskCreate: {
    task_name: string;
    resource_type?: string | null;
    resource_id?: number | null;
    idempotent?: boolean;
    paid?: boolean;
  };
  TaskRunResponse: {
    id: number;
    task_name: string;
    status: "queued" | "running" | "completed" | "failed" | "cancelled" | "interrupted";
    detail: string;
    resource_type: string | null;
    resource_id: number | null;
    queue_job_id: string | null;
    progress: number;
    attempt_count: number;
    max_attempts: number;
    error_code: string;
    cancel_requested: boolean;
    started_at: string | null;
    completed_at: string | null;
    created_at: string;
    updated_at: string;
  };
  ValidationError: {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
  };
}
